Q1: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84\_pos\#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT * WHERE \{     ?v6 dbpowl:abstract ?v1 .     ?v6 geo:lat ?v3 .     ?v6 geo:long ?v4 \} 
Q2: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT * WHERE \{     ?v3 dbpprop:position ?v6 .     ?v3 dbpprop:clubs ?v8 .     ?v8 dbpowl:capacity ?v1 .     ?v3 dbpowl:birthPlace ?v5 \} 
Q3: PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT * WHERE \{     ?v5 dbpowl:thumbnail ?v4 .     ?v5 rdfs:label ?v .     ?v5 foaf:page ?v8 \} 
Q4: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT * WHERE \{     ?v2 rdfs:label ?v .     ?v6 dbpowl:city ?v2 .     ?v6 dbpprop:iata ?v5 \} 
Q5: PREFIX dct: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?v4 dct:subject ?v .     ?v4 foaf:name ?v6 \} 
Q6: PREFIX dct: <http://purl.org/dc/terms/> PREFIX georss: <http://www.georss.org/georss/> PREFIX skos: <http://www.w3.org/2004/02/skos/core\#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?v0 rdfs:comment ?v1 .     ?v0 foaf:page ?v \} 
Q7: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT * WHERE \{     ?var5 dbpowl:thumbnail ?var4 .     ?var5 rdfs:label ?var .     ?var5 foaf:page ?var8 \} 
Q8: PREFIX dbpowl: <http://dbpedia.org/ontology/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT * WHERE \{     ?var8 dbpowl:country ?var6 .     ?var6 foaf:name ?var8 \} 
Q9: PREFIX dbpowl: <http://dbpedia.org/ontology/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT * WHERE \{     ?var9 dbpowl:country ?var .     ?var9 foaf:name ?var4 \} 
Q10: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dbpprop: <http://dbpedia.org/property/> SELECT * WHERE \{     ?var3 dbpprop:series ?var1 .     ?var3 foaf:name ?var4 .     ?var3 rdfs:comment ?var5 .     ?var3 rdf:type ?var0 \} 
Q11: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dbpprop: <http://dbpedia.org/property/> SELECT * WHERE \{     ?var3 dbpprop:series ?var8 .     ?var3 foaf:name ?var4 .     ?var3 rdfs:comment ?var5 \} 
Q12: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> SELECT * WHERE \{     ?var3 dbpprop:numEmployees ?var .     ?var3 foaf:homepage ?var7 \} 
Q13: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> PREFIX dct: <http://purl.org/dc/terms/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?var0 rdfs:comment ?var1 .     ?var0 foaf:page ?var \} 
Q14: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> SELECT * WHERE \{     ?var2 rdf:type ?var1 .     ?var2 dbpprop:population ?var3 \} 
Q15: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> SELECT * WHERE \{     ?var2 rdf:type ?var1 .     ?var2 dbpprop:populationUrban ?var0 \} 
Q16: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?var2 rdfs:label ?var .     ?var6 <http://dbpedia.org/ontology/city> ?var2 \} 
Q17: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?var6 <http://dbpedia.org/ontology/location> ?var2 .     ?var6 <http://dbpedia.org/property/iata> ?var5 \} 
Q18: PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> SELECT * WHERE \{     ?var6 <http://dbpedia.org/ontology/iataLocationIdentifier> ?var5 .     ?var6 foaf:homepage ?var6\_home .     ?var6 <http://dbpedia.org/property/nativename> ?var6\_name \} 
Q19: PREFIX dbpprop: <http://dbpedia.org/property/> SELECT * WHERE \{     ?var dbpprop:subsid ?var3 .     ?var dbpprop:divisions ?var4 \} 
Q20: PREFIX dbpprop: <http://dbpedia.org/property/> SELECT * WHERE \{     ?var dbpprop:divisions ?var4 .     ?var dbpprop:subsid ?var3 \} 
Q21: PREFIX dbpowl: <http://dbpedia.org/ontology/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> SELECT * WHERE \{     ?var2 dbpowl:nationality ?var4 .     ?var4 rdfs:label ?var5 . ?var2 rdfs:label ?var \} 
Q22: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dct: <http://purl.org/dc/terms/> SELECT * WHERE \{     ?var4 dct:subject ?var .     ?var4 foaf:name ?var6 \} 
Q23: PREFIX dct: <http://purl.org/dc/terms/> SELECT * WHERE \{     ?var2 dct:subject ?var .     ?var2 <http://www.w3.org/2000/01/rdf-schema\#label> ?var3 \} 
Q24: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84\_pos\#> SELECT * WHERE \{     ?var6 <http://dbpedia.org/ontology/abstract> ?var1 .     ?var6 geo:lat ?var3 .     ?var6 geo:long ?var4 \} 
Q25: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema\#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84\_pos\#> SELECT * WHERE \{     ?var6 rdfs:label ?var .     ?var6 foaf:depiction ?var8 .     ?var6 foaf:homepage ?var10 \} 
Q26: SELECT * WHERE \{     ?var3 <http://xmlns.com/foaf/0.1/homepage> ?var2 .     ?var3 <http://www.w3.org/1999/02/22-rdf-syntax-ns\#type> ?var \} 
Q27: SELECT * WHERE \{     ?var2 <http://dbpedia.org/ontology/foundationPlace> ?var0 .     ?var4 <http://dbpedia.org/ontology/developer> ?var2 \} 
Q28: PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns\#> SELECT * WHERE \{     ?var6 dbpprop:name ?var0 .     ?var6 dbpprop:pages ?var1 .     ?var6 dbpprop:author ?var3 \} 
