SELECT ?var1 ?var1Label ?var2 ?var3 ?var4 ?var5 ?var6 ?var7 ?var8 ?var9 ?var10 ?var11 ?var12 ?var13 ?var14 ?var15 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P571> ?var2 .     ?var1 <http://www.wikidata.org/prop/direct/P186> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P18> ?var4 .     ?var1 <http://www.wikidata.org/prop/direct/P170> ?var6 } 
SELECT ?var1 ?var1Label ?var2Label ?var3 ?var4 ?var5 ?var6 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q213> .     ?var1 <http://www.wikidata.org/prop/direct/P131> ?var2 .     ?var2 <http://www.wikidata.org/prop/direct/P131> ?var7 .     ?var2 <http://www.wikidata.org/prop/direct/P131> <http://www.wikidata.org/entity/Q579648> } 
SELECT ?var1 ?var2 ?var3 ?var4 ?var5 ?var6Label ?var7 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q34770> .     ?var1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q252> } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P50> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q35064> .     ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q2657001> .     ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P50> ?var2 .     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q571> } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P51> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P50> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P30> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 ?var2 <http://www.wikidata.org/entity/Q828> .     ?var1 <http://www.wikidata.org/prop/direct/P30> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 ?var5 ?var6Label ?var7 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 .     ?var1 <http://www.wikidata.org/prop/direct/P17> ?var3 } 
SELECT ?var1 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P3430> ?var3 .     ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 } 
SELECT ?var1 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6tm93sf" .     ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P1157> ?var1 .     ?var2 <http://www.wikidata.org/prop/direct/P646> ?var4 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P2686> ?var6 .     ?var2 <http://www.wikidata.org/prop/direct/P2390> ?var8 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P1157> ?var1 .     ?var2 <http://www.wikidata.org/prop/direct/P646> ?var4 .     ?var2 <http://www.wikidata.org/prop/direct/P2686> ?var6 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q34770> .     ?var1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q252> } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P305> ?var5 .     ?var1 <http://www.wikidata.org/prop/direct/P1098> ?var7 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P2054> ?var5 .     ?var1 <http://www.wikidata.org/prop/direct/P2067> ?var6 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q811534> .     ?var1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q213> .     ?var1 <http://www.wikidata.org/prop/direct/P131> ?var2 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P131> ?var2 .     ?var2 <http://www.wikidata.org/prop/direct/P131> ?var7 .     ?var2 <http://www.wikidata.org/prop/direct/P131> <http://www.wikidata.org/entity/Q579648> } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P677> ?var4 .     ?var1 <http://www.wikidata.org/prop/direct/P2547> ?var5 } 
SELECT ?var1 ?var2 ?var3 ?var4 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P18> ?var6 .     ?var1 <http://www.wikidata.org/prop/direct/P625> ?var3 } 
SELECT ?var1 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q16521> .     ?var1 <http://www.wikidata.org/prop/direct/P830> ?var4 .     ?var1 <http://www.wikidata.org/prop/direct/P3405> ?var5 } 
SELECT ?var1 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q16521> .     ?var1 <http://www.wikidata.org/prop/direct/P685> ?var2 .     ?var1 <http://www.wikidata.org/prop/direct/P815> ?var3 } 
SELECT ?var1 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q16521> .     ?var1 <http://www.wikidata.org/prop/direct/P815> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P830> ?var4 } 
SELECT ?var1 WHERE {     ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q16521> .     ?var1 <http://www.wikidata.org/prop/direct/P685> ?var2 .     ?var1 <http://www.wikidata.org/prop/direct/P815> ?var3 .     ?var1 <http://www.wikidata.org/prop/direct/P3405> ?var5 } 
SELECT ?var1 WHERE {     ?var2 <http://www.wikidata.org/prop/direct/P31> ?var1 .      ?var2 <http://www.wikidata.org/prop/direct/P212> ?var3 } 
